// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smartsheetapp_netcore.Data;

namespace smartsheetapp_netcore.Migrations
{
    [DbContext(typeof(EventsContext))]
    [Migration("20210112020142_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("smartsheetapp_netcore.Models.EventCallbackModel", b =>
                {
                    b.Property<string>("nonce")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("scope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("scopeObjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("webhookId")
                        .HasColumnType("bigint");

                    b.HasKey("nonce");

                    b.ToTable("EventCallbackModels");
                });

            modelBuilder.Entity("smartsheetapp_netcore.Models.EventModel", b =>
                {
                    b.Property<int?>("eventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cellValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("columnId")
                        .HasColumnType("bigint");

                    b.Property<string>("eventCallbackModelnonce")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("eventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id")
                        .HasColumnType("bigint");

                    b.Property<string>("objectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("rowId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("eventId");

                    b.HasIndex("eventCallbackModelnonce");

                    b.ToTable("EventModels");
                });

            modelBuilder.Entity("smartsheetapp_netcore.Models.StatusChangeCallbackModel", b =>
                {
                    b.Property<string>("nonce")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("newWebhookStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("scopeObjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("webhookId")
                        .HasColumnType("bigint");

                    b.HasKey("nonce");

                    b.ToTable("StatusChangeCallbackModels");
                });

            modelBuilder.Entity("smartsheetapp_netcore.Models.EventModel", b =>
                {
                    b.HasOne("smartsheetapp_netcore.Models.EventCallbackModel", "eventCallbackModel")
                        .WithMany("events")
                        .HasForeignKey("eventCallbackModelnonce");

                    b.Navigation("eventCallbackModel");
                });

            modelBuilder.Entity("smartsheetapp_netcore.Models.EventCallbackModel", b =>
                {
                    b.Navigation("events");
                });
#pragma warning restore 612, 618
        }
    }
}
